### ISSUE TITLE
CubiCal fails to build sharedarray 

### ISSUE THREAD

**Issue by AKHughes1994** [ratt-ru/CubiCal#462] opened 2022-05-06 00:15 UTC
Hi, 

When I try to install CubiCal the installation fails at the current step.

![image](https://user-images.githubusercontent.com/49698839/167046630-655f9347-1694-454d-b923-54eee2ea4ff7.png)

I'll admit, I'm not the most proficient with computers, and googling the warning/errors has done little to help me. Have you every run into an issue like this? Is it an issue with dependancies? 

Thanks for your help,
Andrew

**Comment by JSKenyon** [comment] 2022-05-06 06:54
Hi! Could you please provide some additional information:

1. Which operating system are you using?
2. Which version of Python are you using?
3. Are you inside a virtual environment?
4. Are your `pip`, `setuptools`, and `wheel` packages up to date?
5. Are you installing from source or from PyPI?

I did attempt to reproduce your problem locally but didn't immediately run into problems - the answers to the above will probably help.

One thing I did notice - it looks like the version of `sharedarray` being installed is lower than the minimum requirement for `cubical`.

**Comment by AKHughes1994** [comment] 2022-05-06 15:31
Hi, sorry I should have included this information in my original post, 

1. Ubuntu 18.04 (bionic)
2. Python 3.6.9
3. Yes I'm (attempting to) use a virtual environment
4. pip (21.3.1), setuptools (59.6.0), sharedarray (3.2.1 <- Is this version too low)
5. I'm attempting to install from PyPi

Let me know if you need anymore information,
Andrew

**Comment by JSKenyon** [comment] 2022-05-09 06:52
Apologies for the delayed response!

>     4. pip (21.3.1), setuptools (59.6.0), sharedarray (3.2.1 <- Is this version too low?)

That is the required version of `sharedarray`, but if you look at the log you originally posted, it was attempting to build the wheel for 3.1.0. Are you using a basic Python virtual environment or `pip` inside a conda environment? If you are inside a conda environment, you may need to check that the correct `pip` is in use. You can do this by typing `which pip` - it should point to `pip` inside the virtual environment. If that is not the case, your paths may be incorrect. You can do `echo $PATH` to check.

If I do `pip install --no-cache-dir cubical`, I see the following output for `sharedarray`:
```
Building wheel for sharedarray (setup.py) ... done
  Created wheel for sharedarray: filename=SharedArray-3.2.1-cp36-cp36m-linux_x86_64.whl size=77257 sha256=8e4642d80931853c047a5097af8c7fe64b1dba8551a70c99ebc2a436f0d0f500
  Stored in directory: /tmp/pip-ephem-wheel-cache-cb1vvd85/wheels/40/04/7d/a974a4b947e9f3d7dfb812f41ec8e9e8a8ccd106c8e0314adc
```

**Comment by AKHughes1994** [comment] 2022-05-09 18:45
Adding the `--no-cache-dir` flag worked, thank you. 

I'm not sure what was happening, but I learned all this stuff on the fly so my versions/paths are a mess (I've been meaning to fix that). For some reason it must have been pointing outside the venv.

**Comment by JSKenyon** [comment] 2022-05-10 09:05
All good! Just shout if you need any further assistance. I am going to go ahead and close this for now.

**Closed by JSKenyon** 2022-05-10 09:05 UTC

**Comment by bennahugo** [comment] 2022-10-11 09:01
Can you paste the entire backtrace with compilation failure info?
