### ISSUE TITLE
phase-diag won't load its own gain solutions

### ISSUE THREAD

**Issue by o-smirnov** [ratt-ru/CubiCal#324] opened 2019-10-29 06:37 UTC
As discussed here by @PeterKamphuis: https://github.com/ska-sa/meerkathi/issues/627#issuecomment-547046093

The [intended behaviour](https://github.com/ratt-ru/CubiCal/blob/master/cubical/machines/phase_diag_machine.py#L148) is to load phase, or failing that, load gains and reset the diagonal. So it should be able to load any gain table, never mind its own. Sounds like there's a bug somewhere.

**Comment by PeterKamphuis** [comment] 2019-10-29 08:09
It is also discussed in #315. Just to summarize:

When re-applying gain solutions with xfer-from or load-from the error below occurs when the matrix-type is set to phase-diag (It was set as such when creating the solutions). When the matrix-type is set to complex-2x2 it does not occur. The stesting was done with cubical in stimela but the existence of the error confirmed in the cubical master with a separate installation, the solution only confirmed in stimela. The branch  issue-315 is an attempt by @JSKenyon to solve the error, however it does not seem to actually apply the solutions even though it runs fine. 

Error: 

meerkathi - 2019-09-04 16:54:27,520 INFO - ERROR - 14:54:24 - solver [x03] [0.8/0.9 1.8/2.2 0.9Gb] Solver for tile 0 chunk D0T2F0 failed with exception: Failed in nop
ython mode pipeline (step: nopython frontend)
meerkathi - 2019-09-04 16:54:27,520 INFO - Unknown attribute 'shape' of type none
meerkathi - 2019-09-04 16:54:27,520 INFO -
meerkathi - 2019-09-04 16:54:27,520 INFO - File "../../usr/local/lib/python2.7/dist-packages/cubical/kernels/diag_phase_only.py", line 69:
meerkathi - 2019-09-04 16:54:27,520 INFO - def compute_jhj(m, jhj, t_int=1, f_int=1):
meerkathi - 2019-09-04 16:54:27,520 INFO -
meerkathi - 2019-09-04 16:54:27,521 INFO -
meerkathi - 2019-09-04 16:54:27,521 INFO - n_dir = m.shape[0]
meerkathi - 2019-09-04 16:54:27,521 INFO - ^
meerkathi - 2019-09-04 16:54:27,521 INFO -
meerkathi - 2019-09-04 16:54:27,521 INFO - [1] During: typing of get attribute at /usr/local/lib/python2.7/dist-packages/cubical/kernels/diag_phase_only.py (69)
meerkathi - 2019-09-04 16:54:27,521 INFO -
meerkathi - 2019-09-04 16:54:27,521 INFO - File "../../usr/local/lib/python2.7/dist-packages/cubical/kernels/diag_phase_only.py", line 69:
meerkathi - 2019-09-04 16:54:27,521 INFO - def compute_jhj(m, jhj, t_int=1, f_int=1):
meerkathi - 2019-09-04 16:54:27,521 INFO -
meerkathi - 2019-09-04 16:54:27,521 INFO -
meerkathi - 2019-09-04 16:54:27,521 INFO - n_dir = m.shape[0]
meerkathi - 2019-09-04 16:54:27,521 INFO - ^
meerkathi - 2019-09-04 16:54:27,521 INFO -
meerkathi - 2019-09-04 16:54:27,521 INFO - This is not usually a problem with Numba itself but instead often caused by
meerkathi - 2019-09-04 16:54:27,521 INFO - the use of unsupported features or an issue in resolving types.
meerkathi - 2019-09-04 16:54:27,521 INFO -
meerkathi - 2019-09-04 16:54:27,521 INFO - To see Python/NumPy features supported by the latest release of Numba visit:
meerkathi - 2019-09-04 16:54:27,521 INFO - http://numba.pydata.org/numba-doc/latest/reference/pysupported.html
meerkathi - 2019-09-04 16:54:27,522 INFO - and
meerkathi - 2019-09-04 16:54:27,522 INFO - http://numba.pydata.org/numba-doc/latest/reference/numpysupported.html
meerkathi - 2019-09-04 16:54:27,522 INFO -
meerkathi - 2019-09-04 16:54:27,522 INFO - For more information about typing errors and how to debug them visit:
meerkathi - 2019-09-04 16:54:27,522 INFO - http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile
meerkathi - 2019-09-04 16:54:27,522 INFO -
meerkathi - 2019-09-04 16:54:27,522 INFO - If you think your code should work with Numba, please report the error message
meerkathi - 2019-09-04 16:54:27,522 INFO - and traceback, along with a minimal reproducer at:
meerkathi - 2019-09-04 16:54:27,522 INFO - https://github.com/numba/numba/issues/new

**Comment by KshitijT** [comment] 2019-11-20 16:27
This is sad.  :(
Keep on running head-first into this.

**Comment by o-smirnov** [comment] 2019-11-20 16:32
This is fixed on a branch. How brave are you feeling?

**Comment by KshitijT** [comment] 2019-11-20 16:35
> This is fixed on a branch. How brave are you feeling?

About as much as Courage the Cowardly Dog.
![image](https://user-images.githubusercontent.com/9251962/69257864-6ab58d00-0bc4-11ea-9be3-b452d5eb3dae.png)

But will try it out if you point me to the branch. Can we also drag this is current Stimela, @SpheMakh ? We need this for MeerKATHI. :)

**Comment by PeterKamphuis** [comment] 2019-11-20 16:41
@KshitijT You did pick up that when you set the matrix-type to complex2x2 it seems to work?

**Comment by KshitijT** [comment] 2019-11-20 16:41
> @KshitijT You did pick up that when you set the matrix-type to complex2x2 it seems to work?

Yup, yup.

**Comment by o-smirnov** [comment] 2019-11-21 06:44
issue-326-chisq

**Comment by JSKenyon** [comment] 2019-12-11 12:38
Any luck with the branch @PeterKamphuis @KshitijT?

**Closed** 2020-04-10 21:45 UTC
