### ISSUE TITLE
module 'numba' has no attribute 'set_num_threads'

### ISSUE THREAD

**Issue by viralp** [ratt-ru/CubiCal#426] opened 2020-12-29 10:42 UTC
Hi I am getting the following numba error.
[ddcal_0.log](https://github.com/ratt-ru/CubiCal/files/5750371/ddcal_0.log)

INFO      12:37:18 - main               [0.9 6.1 10.2Gb] Exiting with exception: AttributeError(module 'numba' has no attribute 'set_num_threads')
 Traceback (most recent call last):
  File "/home/parekh/CubiCal/cubical/main.py", line 544, in main
    max_workers=chunks_per_tile)
  File "/home/parekh/CubiCal/cubical/workers.py", line 131, in setup_parallelism
    numba.set_num_threads(int(nthread))
AttributeError: module 'numba' has no attribute 'set_num_threads'

**Comment by o-smirnov** [comment] 2020-12-29 10:47
Yep, looks familiar: https://github.com/ratt-ru/CubiCal/issues/425

I think it's a py2-only issue. Can you make a virtualenv with python3 and try again?

**Comment by JSKenyon** [comment] 2020-12-29 10:50
This error arises because Numba no longer supports Python 2.7, so changes to the thread mechanisms won't propagate back cleanly. Hence me being on-board with dropping support in CubiCal.

**Comment by o-smirnov** [comment] 2021-01-06 10:02
Let's assume this works with py3, and declare it a duplicate of #425...

**Closed by o-smirnov** 2021-01-06 10:02 UTC
