### ISSUE TITLE
montblanc predict crashes (fixed) and nthread>0 causes segfaults

### ISSUE THREAD

**Issue by o-smirnov** [ratt-ru/CubiCal#395] opened 2020-07-10 17:54 UTC
Trying to reacquaint myself with some old VLA data, I get this error with an LSM predict:

```INFO      19:48:37 - main               [2.0 2.0 6.9Gb] Exiting with exception: ValueError(An exception occurred while obtaining data from data source 'point_stokes'

could not broadcast input array from shape (8,128) into shape (5,1024)

'point_stokes' data source information:
    Description: (I,Q,U,V) Stokes parameters.
    Units: Janskys
    Schema or abstract shape: ('npsrc', 'ntime', 'nchan', 4)
            where 'npsrc' is 'point sources'
            where 'ntime' is 'Timesteps'
            where 'nchan' is 'Channels'
    Global shape on this iteration: (4, 11, 1024, 4)
    Local shape for this context: (4, 5, 1024, 4)
    Lower extents within global shape: (0, 6, 0, 0)
    Upper extents within global shape: (4, 11, 1024, 4)


Iteration information:
 ```

Logs/parset/etc. can be found on ``/net/simon//home/oms/projects/VLA-CygA``.

**Comment by JSKenyon** [comment] 2020-07-13 09:32
I have taken a look at this. The offending code is [here](https://github.com/ratt-ru/CubiCal/blob/ad7dc4357ca6c35be169988dd1ff0b33b7757c26/cubical/data_handler/TiggerSourceProvider.py#L153) and [here](https://github.com/ratt-ru/CubiCal/blob/ad7dc4357ca6c35be169988dd1ff0b33b7757c26/cubical/data_handler/TiggerSourceProvider.py#L185). The reason it crashes is because there are eight spectral windows. This means that some of the shapes end up disagreeing, as the Montblanc Stokes array gets something which is `(nband, nchan)` as opposed to `(nband*nchan)`. I have implemented a "fix" in [this branch](https://github.com/ratt-ru/CubiCal/blob/issue-395/cubical/data_handler/TiggerSourceProvider.py). @sjperkins could you please verify that what I am doing isn't going to break things? @o-smirnov your example runs through for me with the changes, though I have no idea if the results are correct.

**Comment by sjperkins** [comment] 2020-07-13 10:27
> I have taken a look at this. The offending code is [here](https://github.com/ratt-ru/CubiCal/blob/ad7dc4357ca6c35be169988dd1ff0b33b7757c26/cubical/data_handler/TiggerSourceProvider.py#L153) and [here](https://github.com/ratt-ru/CubiCal/blob/ad7dc4357ca6c35be169988dd1ff0b33b7757c26/cubical/data_handler/TiggerSourceProvider.py#L185). The reason it crashes is because there are eight spectral windows. This means that some of the shapes end up disagreeing, as the Montblanc Stokes array gets something which is `(nband, nchan)` as opposed to `(nband*nchan)`. I have implemented a "fix" in [this branch](https://github.com/ratt-ru/CubiCal/blob/issue-395/cubical/data_handler/TiggerSourceProvider.py). @sjperkins could you please verify that what I am doing isn't going to break things? @o-smirnov your example runs through for me with the changes, though I have no idea if the results are correct.

Thanks for taking a look at this @JSKenyon. The SourceProvider's need to be set up to return the correct data extents and chunks. It certainly should be possible to configure them, *per DDID*. I have no idea if Cubical's data management loads in multiple DDID's at once. Is this the case? If so, the SourceProviders probably need to be configured to iterate over each one separately.

**Comment by sjperkins** [comment] 2020-07-13 10:30
> I have implemented a "fix" in this branch. @sjperkins could you please verify that what I am doing isn't going to break things?

I'm unsure about the ravelling of ``self._freqs[lc:uc]`` since my current understanding of it as a 1D (nchan,) array of CHAN_FREQ. Has a getcol been changed to a getvarcol somewhere and introduced the extra singleton row. i.e. (row, nchan)?

**Comment by o-smirnov** [comment] 2020-07-13 10:37
I'm a bit confused too. We iterate over DDIDs, right? So it's only ever called for one DDID at a time. Where does the extra ``nband`` dimension come in?

**Comment by o-smirnov** [comment] 2020-07-13 10:42
Ah no, wait, we actually set up the simulation per tile, which means a bunch of DDIDs are predicted together.

**Comment by JSKenyon** [comment] 2020-07-13 11:10
Precisely - I think we just stack them along the frequency axis.

**Comment by o-smirnov** [comment] 2020-07-13 11:20
Strangely, I'm getting it to segfault now, with only a few changes to the options. @JSKenyon could you run it with ``cyg.parset`` please to see if you get the same?

**Comment by JSKenyon** [comment] 2020-07-13 11:43
Working on it - I did see the process pool crash out, but I suspect it happens when `nthread` is greater than 1.

**Comment by o-smirnov** [comment] 2020-07-13 11:45
Ah of course, that must be the crucial change. But does this mean that Montblanc threading is broken?

**Comment by JSKenyon** [comment] 2020-07-13 11:52
I don't think it is dying in Montblanc - still working on it.

**Comment by JSKenyon** [comment] 2020-07-13 12:03
Yeah - this definitely makes it to the solver before dying.

**Comment by JSKenyon** [comment] 2020-07-13 12:04
The issue is likely something in a numba kernel.

**Comment by JSKenyon** [comment] 2020-07-13 12:13
The crash is happening in [this line](https://github.com/ratt-ru/CubiCal/blob/ad7dc4357ca6c35be169988dd1ff0b33b7757c26/cubical/solver.py#L147).

**Comment by o-smirnov** [comment] 2020-07-13 12:17
Lovely. Seems like the simplest kernel of them all, right?

**Comment by JSKenyon** [comment] 2020-07-13 13:05
Hmmm, this is proving to be far, far stranger that I would have anticipated.

**Comment by JSKenyon** [comment] 2020-07-13 13:12
Something is VERY dodgy when using parallel kernels and caching.

**Comment by JSKenyon** [comment] 2020-07-13 14:15
@o-smirnov Giving up on this one for today - I am downloading the test data to my local machine to speed up testing. There is some weird stuff happening, such as arrays having their shapes changed when they enter the numba layer.

**Comment by bennahugo** [comment] 2020-07-13 14:23
Are you guaranteeing that the arrays are c contiguous for the shape you
want? You may need to make sure the .copy() is called

**Comment by o-smirnov** [comment] 2020-07-13 15:06
Interesting! I can always run single-threaded, of course, but it would be nice to find the problem.

**Comment by sjperkins** [comment] 2020-07-13 15:29
> Are you guaranteeing that the arrays are c contiguous for the shape you want? You may need to make sure the .copy() is called

I think numba handles this OK:

```python
import numba
import numpy as np

@numba.njit
def fn(a):
    result = a.dtype.type(0)

    for i in range(a.shape[0]):
        for j in range(a.shape[1]):
            result += a[i, j]

    return result

data = np.ones((20, 20)).T
assert data.flags.c_contiguous is False
assert fn(data) == data.sum()
```

**Comment by bennahugo** [comment] 2020-07-13 16:03
Ok nvm. Just thought it might be the reason for segfaulting

**Comment by JSKenyon** [comment] 2020-07-14 07:55
This appears to be some sort of regression in Numba - segfault appears from `0.49` onward.  [This issue](https://github.com/numba/numba/issues/5890) seems to be the problem. Setting `--dist-nthread` to the number of cores (both physical and virtual) on my laptop makes the problem go away. You can see my replies to that issue for more details. In the mean time @o-smirnov, you can downgrade to `numba==0.48`.

**Comment by o-smirnov** [comment] 2020-07-14 08:11
Scary! Or I can not use threads, I guess...

**Comment by JSKenyon** [comment] 2020-07-14 08:22
For CubiCal (as opposed to QuartiCal), downgrading shouldn't be at all problematic - we aren't really using the newer features inside the kernels.

**Comment by JSKenyon** [comment] 2020-07-15 09:06
Just an quick update - the Numba devs are being really helpful. They have managed to reproduce the issue but it seems like it might be a complicated one. For now avoid using threads/downgrade Numba to `0.48`.

**Comment by JSKenyon** [comment] 2020-07-23 07:25
@o-smirnov I think this is fixed in the PR I just put up. Can you please take a look when you have a moment?

**Closed** 2020-07-23 09:16 UTC
Labels: bug
