### ISSUE TITLE
The selected DDID/frequencies in this MS are not laid out monotonically

### ISSUE THREAD

**Issue by AKHughes1994** [ratt-ru/CubiCal#464] opened 2022-06-13 19:15 UTC
I'm getting this error when running CubiCal on some VLA data, and it's killing all runs almost immediately, 

![image](https://user-images.githubusercontent.com/49698839/173427455-0386269f-4d95-47b1-bf8f-c0cc5bfccfed.png)

I'm not sure if I'm misinterpreting the error (I'm not exactly sure what DDID stands for) but my frequencies are absolutely laid out Monotonically, it's just 8-bit S-Band VLA data (I flagged the first 3 Spws due to RFI) but the data increases from CtrFreq = 2435MHz to 3947MHz from spw 0 to 12. 

Any advice on how to Debug this issue? 
Cheers,
Andrew

**Comment by IanHeywood** [comment] 2022-06-13 20:02
DDID = Data Description ID, which is most cases is just synonymous with spectral window.

Do the SPWs all have equivalent channel widths? What does the output of CASA's listobs say?

You could also try iterating over SPWs sequentially with CubiCal, using `--sel-ddid`.

**Comment by AKHughes1994** [comment] 2022-06-13 21:14
The output is pretty typical of VLA observations, 

![image](https://user-images.githubusercontent.com/49698839/173445132-380852bf-00a2-47b5-bb21-1be4286221e9.png)

Excluding flagging, each SPW has  64x 2 MHz = 128MHz bandwidth, the lower the SPW ID the lower the central frequency. I was playing around with --sel-ddid and it works with '0~4' and '5~12', since I flagged the first three SPWS this  actually corresponds to the two base-bands of the original 16 SPW VLA observations, despite the there the transition in frequency between monotonic.

**Comment by JSKenyon** [comment] 2022-06-14 06:57
Hi @AKHughes1994! I am not entirely sure what would be going wrong here. The error message you are seeing comes from here:

https://github.com/ratt-ru/CubiCal/blob/59f28596150d15e4d673fd07999050e770d00fb2/cubical/data_handler/ms_data_handler.py#L499-L504

It is possible that this check is slightly wrong, but it will be tricky to fix without access to your data.

> Is there a way to append the two solution intervals for a single directory? If I run 0~4, then 5~12 refuses to run since my directory already exists, or do I just rename the directory?

You could just output the second set to second directory. I appreciate this may not be convenient though (depending on what further processing you want to do).

**Comment by AKHughes1994** [comment] 2022-06-14 18:30
If you are interested in the data

You should be able to download the ms file from this link,

https://drive.google.com/file/d/1zyXpEbECz4J_vXIC1AljdXcHFItWEJNU/view?usp=sharing

**Comment by JSKenyon** [comment] 2022-06-14 19:02
Great! Could you please provide your parset? That should be enough for me
to figure it out.

**Comment by JSKenyon** [comment] 2022-06-15 07:46
Ok, I have managed to reproduce. The issue is that SPW4 and SPW5 overlap. Largest `CHAN_FREQ` in SPW4 is 3.010GHz, smallest in SPW5 is 2.988GHz. CubiCal concatenates along the frequency axis and doesn't know how to handle this situation. Depending on what you are doing, you could try [QuartiCal](https://github.com/ratt-ru/QuartiCal). It processes each SPW separately (which is sensible for the VLA).

Alternatively, you can process the your data in two passes. You could use `--sel-ddid=0~4` and `--sel-ddid=5~12` to skirt around the problem.

Another approach would be to split the problem into two measurement sets and simply image them simultaneously. 

Hope this helps - it is not so much a bug as a limitation in CubiCal.

**Comment by o-smirnov** [comment] 2022-06-15 15:14
Anyone have suggestions for a better error message in this case?

**Comment by JSKenyon** [comment] 2022-06-17 07:00
"The selected spectral windows (DDIDs) in this MS are not laid out monotonically and/or overlap. This is not currently supported. Consider using --sel-ddid to process a single spectral window/range of spectral windows independently."

**Comment by AKHughes1994** [comment] 2022-06-17 20:10
Thank you for the clarification, just breaking it into two interactions is
a very easy work around!

**Comment by JSKenyon** [comment] 2022-10-31 07:21
Closing as I think this is "resolved".

**Closed by JSKenyon** 2022-10-31 07:21 UTC
