### ISSUE TITLE
Multiple model visibility columns

### ISSUE THREAD

**Issue by SpheMakh** [ratt-ru/CubiCal#83] opened 2017-10-25 14:59 UTC
As discussed earlier with @JSKenyon, it would be useful to be able specify multiple model visibility columns. And even better to be able to select some of these columns for DD treatment

Possibly something like this:

```
model-di-column = <list of columns with data to be used for di sols>
model-dd-column = <list of columns with data to be used for dd sols; subset of model-di-column if it exists>
```

**Comment by o-smirnov** [comment] 2017-10-25 15:02
I have anticipated your every wish, and more: https://github.com/ratt-ru/CubiCal/issues/5

PR coming soon. Closing this, as it is a duplicate of #5 effectively.

**Closed by o-smirnov** 2017-10-25 15:02 UTC

**Comment by IanHeywood** [comment] 2017-10-25 17:41
I was also daydreaming about this capability earlier. You're like radio astronomy Santa.

**Comment by o-smirnov** [comment] 2017-10-26 05:00
If you're feeling lucky, punks, try the ``issue-5`` branch (this includes ``ifr-gains``, so will have all the channel selection etc.) fixes.

**Comment by o-smirnov** [comment] 2017-10-26 15:16
Better, use the ``ifr-gains`` branch. I merged in the issue-5 fixes, and a lot of other neat stuff.
